# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "SRB"

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: "SRB"

### Social
social:
  - title: "Twitter"
    icon: "fab fa-twitter"
    url: "http://twitter.com/cardedubenefits"

### Footer
footer:
  developer: "Dezvoltat de <strong>chenist.digital</strong>"
  copyright: "<strong>EduBenefits</strong>. Toate drepturile rezervate."

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Educatie"
      slug: "educatie"

    - name: "sanatate"
      slug: "sanatate"

    - name: "Servicii"
      slug: "servicii"

    - name: "Ospitalitate"
      slug: "ospitalitate"

    - name: "Timp liber"
      slug: "timp-liber"

    - name: "Transport"
      slug: "transport"

    - name: "Sport"
      slug: "sport"

    - name: "Produse"
      slug: "produse"

    - name: "Animale"
      slug: "animale"

    - name: "Servicii firme"
      slug: "servicii"

    - name: "Alte servicii"
      slug: "alte-servicii"

    - name: "Constructii / amenajari"
      slug: "constructii"